### PR TITLE
Command allows for an array for long commands.

### PR DESCRIPTION
**Pull request by lgracia-lifesize**

### CODE REVIEW

**Comment by benoror** [comment]
@lgracia-lifesize could you provide more info regarding your need for this kind of functionality?

**Comment by lgracia-lifesize** [comment]
@benoror that would be for long commands. We are looking at the option to implement a flat structure for test cases and use mocha -g to search for test names, the list of tests would be too long for one line, specially if using prettier with 80 chars limit. It would be just to have that option of separating the command into multiple lines.

**Comment by lgracia-lifesize** [comment]
@benoror I thought about that but I would need two scripts, one for windows and one for mac, and then use an env variable to decide which one to run. In my case it would be easier to have multi-line command instead of a script.

**Comment by galenandrew** [comment]
I agree that having a file with your command/script is a better approach in general. It's a lot easier to maintain a script file than a long script in a JSON file broken out into an array.

**Comment by benoror** [comment]
> I agree that having a file with your command/script is a better approach in general. It's a lot easier to maintain a script file than a long script in a JSON file broken out into an array.
> 
>  👍 1

Agree! @lgracia-lifesize maybe you could come up with a way to run script files cross-OS compatible?

Also I would suggest you to checkout https://github.com/kentcdodds/cross-env

In the meantime I'll close this PR, thanks for it anyways!

**Pull request closed without merging**
