### PR TITLE
convert from dos line endings to unix

### PR DESCRIPTION
**Pull request by gorangajic**
so we can run better-npm-run directly
```better-npm-run start```
instead of
```node ./node_modules/.bin/better-npm-run start```

### CODE REVIEW

**Comment by gorangajic** [comment]
btw this fixes #5

**Comment by benoror** [comment]
Thanks!

**Comment by kentcdodds** [comment]
Sweet!! Thanks @benoror :D

**Comment by kentcdodds** [comment]
And by that I mean "Thanks @gorangajic for fixing it and thanks @benoror for merging it and creating this tool" :-)

**Comment by benoror** [comment]
:smile: the beauty of OSS

**Comment by arkist** [comment]
good!
@benoror :shipit: plz

**Pull request merged**
