### PR TITLE
Update readme with new alternatives added

### PR DESCRIPTION
**Pull request by iamyoki**
Hi, this PR adds a new alternative tool - [better-scripts](https://github.com/iamyoki/better-scripts). I am the author by the way 👋..

I created better-scripts recently then I discovered this one is very similar.

Read more about better-scripts on [Official Docs](https://better-scripts.vercel.app/).

### CODE REVIEW

**Comment by benoror** [comment]
The original aim of this project was to provide cross-platform compatibility when running scripts. As stated in https://github.com/benoror/better-npm-run/issues/85 seems that this just provides chalk on top of it

**Comment by iamyoki** [comment]
@benoror Actually, it supports cross-platform as well, and It's just the tip of the iceberg. 
https://better-scripts.vercel.app/docs/configuration#script-object
image

If you look at the source code, the logic is the same as that of cross-env.
https://github.com/iamyoki/better-scripts/blob/8d3d8df5781e437123d872a946fad4136117933e/lib/runScript.js#L30-L33

And it's not just a "chalk".

**Comment by benoror** [comment]
Ok, seems that's referring to x-plat for env variables only. If you look at before-mentioned codebases they contain substantial code to deal with different platforms, specially tricky win32 configurations:

https://github.com/benoror/better-npm-run/blob/7510a5cba803bc96c4e24032e6a21f79cf348535/lib/exec.js#L26-L41

https://github.com/kentcdodds/cross-env/blob/3edefc7b450fe273655664f902fd03d9712177fe/src/command.js#L14-L32

How does that compares with your valid yet different goal/featureset?

**Comment by iamyoki** [comment]
Thank you, suggestions are open.
`windowsVerbatimArguments ` is not required due to `shell: true` according to [Node API here](https://nodejs.org/api/child_process.html#child_processspawnsynccommand-args-options)
```
windowsVerbatimArguments [<boolean>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Boolean_type) No quoting or escaping of arguments is done on Windows. Ignored on Unix. This is set to true automatically when shell is specified and is CMD. Default: false.
```

But your suggestion is very helpful, I just modified the shell to only take effect on platform 32.
https://github.com/iamyoki/better-scripts/commit/2e0539c8da0cafc23a99de9698c3b3199c51e80f#

**Pull request closed without merging**
