### PR TITLE
Proposed solution for issue #56

### PR DESCRIPTION
**Pull request by hrimhari**
Should solve https://github.com/benoror/better-npm-run/issues/56

### CODE REVIEW

**Comment by galenandrew** [comment]
@hrimhari thank you for taking the time to propose this solution! Because this Pull Request is introducing a completely new concept of `defaultEnv` into the package, it will require further consideration and discussion before merging.

**Comment by hrimhari** [comment]
Keep in mind that this pull is fully backward compatible with the behavior everyone expected regarding `betterScripts.[script-name].env` and addresses the need expressed by @just-boris.

**Comment by just-boris** [comment]
No, it doesn't resolve my need.

I need to have a place where I can put overrides out of version control, i.e. not in the `package.json`. So this will not work.

**Comment by hrimhari** [comment]
That's exactly what it does, except that the package.json part that gets overriden is `defaultEnv` instead of `env`.

**Comment by just-boris** [comment]
Maybe I don't understand something, how am I supposed to change some value either in env or defaultEnv without making `package.json` file alarmed by GIT, that it was changed?

**Comment by hrimhari** [comment]
`defaultEnv` would provide 'default' values for env variables that are not defined elsewhere. Any other place would be able to override that, being the `.env` file, `process.env` or `betterScripts.[script-name].env`. Your use-case would be covered by defining your `PORT` variable under `defaultEnv` and having it overridden by your `.env` file.

At the same time, the behavior that everybody else loves about `betterScripts.[script-name].env` is maintained, which is to not be overridden by anybody.

**Comment by just-boris** [comment]
@hrimhari Got this, now the use-case is clear for me. Thank you for taking your time!

One final question: why do you want so much to protect env variables? Is there any security concern or what? 

For me, it seems like making a system less flexible. Initially, if you are reading some environment variables that means that you want some configuration here. At next step, you are freezing those options via assigning `betterScripts.[script-name].env` highest priority. What is the reason to define variables at the first time? Seems like unnecessary complexity.

**Comment by galenandrew** [comment]
Closing in reference to **[Intended Behavior & Use-Case](https://github.com/benoror/better-npm-run/issues/56#issuecomment-256709687)**.

If you'd like to propose adding `defaultEnv` as an option, please open an issue for further discussion.

**Pull request closed without merging**
