### PR TITLE
Pipe stdout, stderr

### PR DESCRIPTION
**Pull request by jhen0409**
Use `stdio: ['pipe', process.stdout, process.stderr]`, it will be easier and solve problem of no output colors.

Before:

After:

### CODE REVIEW

**Comment by benoror** [comment]
Looks good so far, any chance to test it in a Windows env?

(cc @gorangajic @jonaskello @christianharke win test would be appreciated :smiley: )

**Comment by jhen0409** [comment]
It originally seems already has problems in Windows, if we use `npm list` in `betterScripts`, it will be not work on Windows.

Maybe we can add `cmd /c` to head (Unix: sh -c), @benoror what do you think?

**Comment by benoror** [comment]
What do you mean running `npm list` in Win doesn't work?

I tried your PR and seems to work well on Linux and Windows, I added the following test:

```
if(!chalk.supportsColor) {
    console.log('No colors supported');
}
console.log('All '+chalk.green('tests')+' passed');
```

(I test color support with [chalk.](https://github.com/chalk/chalk#chalksupportscolor))

See the results in both Win & Ubuntu:

betterwin

betterlin

I created a separate branch for this, can you try it?

**https://github.com/benoror/better-npm-run/tree/issue24**

**Comment by jhen0409** [comment]
The `bash.exe` no problem on Windows, but I use `cmd` it not work:
test

I think we should support `cmd`. I added the `cmd /c` (and `sh -c`) to command head, it work well. I'll push new commit.

**Comment by benoror** [comment]
Cool, just make sure it only fallbacks to it when using Windows + cmd.exe, we don't want to break Unix users.

Also remember some scripts run on CI servers, therefore color support is dispensable

**Comment by jhen0409** [comment]
It's done. :D

**Comment by quicksnap** [comment]
Just ran into this issue on Windows and used this patch--works like a charm.

**Comment by benoror** [comment]
Released as [0.0.5](https://github.com/benoror/better-npm-run/releases/tag/0.0.5)

**Pull request merged**
