### PR TITLE
Use dot-env package

### PR DESCRIPTION
**Pull request by gillescastel**
Is this okay?

Note that

```javascript
require('dotenv').config();
```

will throw a warning when no `.env` file is present. Would suppressing the warning be better?

```javascript
require('dotenv').config({silent: true});
```

### CODE REVIEW

**Comment by carnesen** [comment]
Yes, the warning should be suppressed.

**Comment by gorangajic** [comment]
Great @gillescastel thanks

**Comment by benoror** [comment]
lgtm thanks guys!

**Comment by benoror** [comment]
released in: [0.0.7](https://github.com/benoror/better-npm-run/releases/tag/0.0.7)

**Pull request merged**
