### PR TITLE
change to spawn and read .env

### PR DESCRIPTION
**Pull request by gorangajic**
I have included spawn from pull request #14 
and changed pull request #17 upon your request

### CODE REVIEW

**Comment by gorangajic** [comment]
@benoror it would be great if you can merge this and publish npm package

Thanks

**Comment by benoror** [comment]
@gorangajic sorry I was busy with work :worried: 

At first glance the code looks good, nevertheless I pulled your code and tested it. I have a simple repo for testing purposes: [benoror/better-npm-run-test-repo](https://github.com/benoror/better-npm-run-test-repo), which is failing with the following error:

```
benoror:~/github/better-npm-run-test-repo | master
$ npm test

> better-npm-run-test-repo@1.0.0 test /home/benoror/github/better-npm-run-test-repo
> node node_modules/.bin/better-npm-run test

running better-npm-run in /home/benoror/github/better-npm-run-test-repo
Executing script: test

/home/benoror/github/better-npm-run/lib/exec.js:17
	var env = Object.assign(process.env, script.env, dotenv);
	                 ^
TypeError: undefined is not a function
    at exec (/home/benoror/github/better-npm-run/lib/exec.js:17:19)
    at Object.<anonymous> (/home/benoror/github/better-npm-run/index.js:28:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```

**Comment by gorangajic** [comment]
Thats because node version, I was using es6 lately so I forget that Object.assign is not available in old versions of node.
Will update code quickly

**Comment by benoror** [comment]
that would be great, I love ES6 but many projects still rely on ES5 & 0.12.7 for compatibility (I can think of 2 atm)

Thanks!

**Comment by benoror** [comment]
Thanks for a fantastic PR @gorangajic :clap: :tada:

**Pull request merged**
