### PR TITLE
feature: substitute environment variables + 2sp indents

### PR DESCRIPTION
**Pull request by bguiz**
Same as https://github.com/benoror/better-npm-run/pull/50 
... plus changes all tabs to 2 space for indentation

### CODE REVIEW

**Comment by benoror** [comment]
@bguiz thanks for you contribution, the code seems good so far, nevertheless do you mind:

- Using Fast-forward to avoid merge commits
- Rebase interactive to Squash/Fix commits (identation fix)
- Dropping the '=BG=' from the commit messages
- Use atomic commits to facilitate the PR Review
- There's no need to create a separate PR each time, you can `git push --force` :)

I don't want to seem picky but there is an implicit **etiquete** for contributing to OSS. Hope it's not a pain in the ass 🙈 

- https://stories.devacademy.la/how-to-use-github-like-a-proper-human-being-1a9c895c4e13#.4069xf24x
- http://chris.beams.io/posts/git-commit/
- https://github.com/agis-/git-style-guide

Let me know if you need any help! 😄

**Comment by galenandrew** [comment]
@bguiz there have been some changes to the package recently. Please revise this Pull Request and resubmit. If not, we will close due to inactivity. Thanks!

**Comment by super-cache-money** [comment]
@bguiz Really unfortunate this never made it in, it'd be super neat

**Comment by bguiz** [comment]
@super-cache-money https://github.com/bguiz/erun might fit your needs

**Pull request closed without merging**
