### PR TITLE
Add support for command string

### LINKED ISSUE #47: Add support for command string instead of sub-object.
Hey @benoror! Cool package here! Would you be open to considering a PR that adds support for a command string vs sub-object?

For instance instead of:
```JSON
"betterScripts": {
    "some-nom-script": {
        "command": "node ./my-script.js"
    }
}
```

it could be…
```JSON
"betterScripts": {
    "some-nom-script": "node ./my-script.js"
}
```

The use case/value here is to simplify the `betterScripts` object when you don't have env variables to declare (because they are in a `.env` file).

Let me know, and if you're open to it I'll submit a PR.

### PR DESCRIPTION
**Pull request by galenandrew**
This Pull Request adds support for accepting a string in the `betterScripts` script definition as well as updates the README with a usage example.

_Note: I also broke out the tests into separate commands/scripts so that each feature could be tested. Let me know if you want me to pull this out and revert the tests._

fixes #47

### CODE REVIEW

**Comment by benoror** [comment]
Thanks a lot @galenandrew! 👏 👏  , gonna check it out during the weekend (hopefully)

**Comment by galenandrew** [comment]
Sounds good! If you have any questions, just @ mention me…I should be able to respond pretty quickly.

**Comment by galenandrew** [comment]
@benoror any luck reviewing this? Totally understand if things got busy or you need more time.

**Comment by benoror** [comment]
@galenandrew Andrew I just had a chance to review this, it's awesome! Sorry for the delay, and thanks for the contribution! Would yo be interested in becoming a repo maintainer?

**Pull request merged**
