### PR TITLE
add ability to read .env from the project root

### PR DESCRIPTION
**Pull request by gorangajic**
I have like 4-5 commands that share NODE_PATH=./lib so it will be good to share that env somehow

### CODE REVIEW

**Comment by benoror** [comment]
Hey @gorangajic , thanks for the PR, this sounds like a reasonable feature, but I quick search gave me some modules that already handle this, like:

- https://github.com/motdotla/dotenv
- https://github.com/grimen/node-env-file

I am inclined to avoid complexity by not reinventing the wheel, following unix phillosophy ([DOTADIW](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well))

Could you update your PR to make use an appropiate package?

Thanks a lot in advance!

**Comment by gorangajic** [comment]
I have searched for something similar before making pull request, they both inject env variables into current node.js process

Not sure how to handle this differently? Maybe I can create ```read-dot-env``` npm module or ./lib/read-dot-env that will read .env if available and return env object that script.env can be extended to?

**Comment by benoror** [comment]
Ok got it.

Maybe it's not worth to create a separate module just for reading the file, maybe just refactoring is enough, creating a new file `lib/dot-env.js` and consuming it like:

```
dotEnv = require('./dot-env');
...
command_line = dotEnv.toString() command_line;
```

Please also consider keeping compatibility with win32 style for setting env vars, and the intention to merge https://github.com/benoror/better-npm-run/pull/14 & https://github.com/benoror/better-npm-run/pull/17

**Comment by benoror** [comment]
Fixed via https://github.com/benoror/better-npm-run/pull/19

**Pull request closed without merging**
